name: Main CI WorkFlow
on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  verify:
    name: Verify Project
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: go get -v -t -d ./...

      - name: Install Lint
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          version: latest

      - name: Go Test
        run: go test -v ./...

      - name: Check Lint
        run: golangci-lint run ./...

  build:
    name: Build Project
    needs: verify
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build
        run: go build -ldflags="-s -w" -installsuffix cgo -o bot github.com/zc2638/review-bot/cmd